[project]
name = "dictmaker"
version = "2026.1.7"
description = "Dictionary generator for anki cards"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }