[project]
name = "shared"
version = "0.1.1"
requires-python = ">=3.14"
dependencies = []

[tool.hatch.build.targets.wheel]
sources = ["."]
rewrite-path = "shared"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
